name: Run tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv6

    steps:
    - uses: actions/checkout@v1

    - uses: uraimo/run-on-arch-action@v2.0.5
      name: Run commands
      id: runcmd
      with:
        arch: armv6
        distro: ubuntu18.04

        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}

        # Set an output parameter `uname` for use in subsequent steps
        run: |
          uname -a
          echo ::set-output name=uname::$(uname -a)

        - name: Cache choosenim
          id: cache-choosenim
          uses: actions/cache@v1
          with:
            path: ~/.choosenim
            key: ${{ runner.os }}-choosenim-stable

        - name: Cache nimble
          id: cache-nimble
          uses: actions/cache@v1
          with:
            path: ~/.nimble
            key: ${{ runner.os }}-nimble-stable

        - uses: jiro4989/setup-nim-action@v1

        - run: nimble test -y

    - name: Get the output
      # Echo the `uname` output parameter from the `runcmd` step
      run: |
        echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
